### ISSUE TITLE
เมื่อเลือกชื่อหนังแล้ว อยากให้แสดงรายละเอียดของหนังเรื่องด้วย

### ISSUE THREAD

**Issue by naruepat** [Aquzohr/exercise#1]
- ชื่อหนัง
- ราคา
- รูปภาพ

![screen shot 2561-05-14 at 11 14 39](https://user-images.githubusercontent.com/5475736/39978014-3144cc82-5768-11e8-8487-a1d35a03c755.png)

**Comment by Aquzohr** [comment]
https://github.com/Aquzohr/exercise/commit/6ff56060620c3c735a271eb7c796dcfe8fbe64e6

**Comment by naruepat** [comment]
ok ครับผม
