### ISSUE TITLE
แสดงข้อมูลเงินทอน เป็น UI ที่ดูง่ายขึ้น

### ISSUE THREAD

**Issue by naruepat** [Aquzohr/exercise#2]
![screen shot 2561-05-14 at 11 17 09](https://user-images.githubusercontent.com/5475736/39978064-82a6c80a-5768-11e8-9925-0b21eab93c0f.png)

**Example**
Change Payment : 636
500 x 1
100 x 1
20 x 1
10 x 1
5 x 1
1 x 1

--------------------------
Change Payment : 800
500 x 1
100 x 3

**Comment by Aquzohr** [comment]
3c24f33087c458a3c2b48e07c20e34f6b1da575b

**Comment by naruepat** [comment]
โอเคครับผม
