### ISSUE TITLE
กรอกได้เฉพาะจำนวนเต็มเท่านั้น พร้อมแสดง ข้อความด้านล่าง input

### ISSUE THREAD

**Issue by naruepat** [Aquzohr/exercise#4]
![screen shot 2561-05-17 at 15 52 11](https://user-images.githubusercontent.com/5475736/40167087-4bd5eab6-59ea-11e8-9f0e-98a1b4017efa.png)

ต้องการใช้เช็คหากกรอกตัวเลขน้อยกว่า 1 จะแสดงข้อความด้านล่าง input นั้นๆ ว่า "กรุณากรอกตัวเลขมากกว่า 0 เท่านั้น"

**Comment by Aquzohr** [comment]
593fb34508211ec6cdd5c04396e72750e280a49b

อันนี้ก็ไม่ทรายเหมือนกันนะครับ เวลา input ในช่อง ticket แล้วมันไม่แจ้งเตือนอะไรเลย

แต่ถ้าเป็น cash ใช้ได้ปกครับ

**Comment by Aquzohr** [comment]
aca858987793e924d30e5cff4b5ddc5ae8d59881 แก้ได้ละครับ ส่งสัยมัน return ผิดที่

**Comment by Aquzohr** [comment]
8909f11ae4e6a85a98dcdf95073ed218c8ff8dac แก้เงื่อนไขนิดหน่อยครับ

**Comment by naruepat** [comment]
โอเคครับผม
